//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KrysenkoLEGOShop.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Address
    {
        public Address()
        {
            this.Clients = new HashSet<Client>();
        }
    
        public int ID { get; set; }
        public string Town { get; set; }
        public string Street { get; set; }
        public Nullable<int> Home { get; set; }
        public Nullable<int> Apartment { get; set; }
    
        public virtual ICollection<Client> Clients { get; set; }
    }
}
