//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KrysenkoLEGOShop.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public Order()
        {
            this.ProductOrders = new HashSet<ProductOrder>();
        }
    
        public int ID { get; set; }
        public System.DateTime Date { get; set; }
        public System.TimeSpan Time { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual DeliveryWay DeliveryWay { get; set; }
        public virtual Payment Payment { get; set; }
        public virtual ICollection<ProductOrder> ProductOrders { get; set; }
    }
}
